branches:
  only:
  - test
  - /^release-.*$/
  - /.*-travis$/
  - master

os: linux
dist: bionic # Ubuntu 18.04

before_install:
  - export DEBIAN_FRONTEND=noninteractive
  - sudo apt install g++ pkg-config build-essential wget libopenmpi-dev sqlite3 wget libssl-dev zlib1g-dev libncurses5-dev libncursesw5-dev libreadline-dev libsqlite3-dev libgdbm-dev libdb5.3-dev libbz2-dev libexpat1-dev liblzma-dev libffi-dev -y
  - sudo apt-get install make -y
  - sudo apt-get install jasper -y
  - sudo apt install python3.7 python3-pip -y
  - wget https://github.com/sheecegardezi/ubuntu-package-binaries/raw/master/proj_6.2.1-1_amd64.deb
  - sudo apt install /home/travis/build/GeoscienceAustralia/PyRate/proj_6.2.1-1_amd64.deb
  - wget https://github.com/sheecegardezi/ubuntu-package-binaries/raw/master/gdal_3.0.2-1_amd64.deb
  - sudo apt install /home/travis/build/GeoscienceAustralia/PyRate/gdal_3.0.2-1_amd64.deb
  - export CPLUS_INCLUDE_PATH=/usr/include/gdal
  - export C_INCLUDE_PATH=/usr/include/gdal
  - export LC_ALL=C.UTF-8
  - export LANG=C.UTF-8

install:
  - sudo sh -c "echo '/usr/local/lib' >> /etc/ld.so.conf"
  - sudo ldconfig
  - cd /home/travis/build/GeoscienceAustralia/PyRate
  - python3 -m pip install --upgrade setuptools
  - cd /home/travis/build/GeoscienceAustralia/PyRate
  - sudo python3 setup.py install
  - sudo python3 -m pip uninstall GDAL -y
  - sudo python3 -m pip install GDAL==$(gdal-config --version)

# command to run tests
script:
  - cd /home/travis/build/GeoscienceAustralia/PyRate
  - python3 -m pytest --version
  - python3 -m pytest tests/ -svv; echo $?

after_success:
  - python3 -m codecov

notifications:
  email:
    recipients:
      - $SHEECE_EMAIL
    on_success: never
    on_failure: always
